apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wine-quality-predictor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/surajkunwarkcgi/complete-mlops-project
    targetRevision: main
    path: Model/k8s  # ArgoCD watches only this subfolder
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true