apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mlflow-secret-provider
  namespace: mlops
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "mlflow-tracking-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: MLFLOW_TRACKING_URI
            objectAlias: MLFLOW_TRACKING_URI
          - path: MLFLOW_TRACKING_USERNAME
            objectAlias: MLFLOW_TRACKING_USERNAME
          - path: MLFLOW_TRACKING_PASSWORD  
            objectAlias: MLFLOW_TRACKING_PASSWORD
  secretObjects:
    - secretName: mlflow-secrets
      type: Opaque
      data:
        - objectName: MLFLOW_TRACKING_URI
          key: MLFLOW_TRACKING_URI
        - objectName: MLFLOW_TRACKING_USERNAME
          key: MLFLOW_TRACKING_USERNAME
        - objectName: MLFLOW_TRACKING_PASSWORD
          key: MLFLOW_TRACKING_PASSWORD