apiVersion: v1
kind: ServiceAccount
metadata:
  name: wine-quality-predictor
  namespace: mlops
  annotations:
    # TODO: Replace with output of: terraform output wine_quality_predictor_iam_role_arn
    eks.amazonaws.com/role-arn: