apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wine-quality-predictor
  namespace: mlops
spec:
  namespaceSelector:
    matchNames:
      - mlops
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app: wine-quality-predictor
    